# Generated by Django 3.2.2 on 2021-06-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aticles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300, unique=True)),
                ('title', models.CharField(max_length=300, unique=True)),
                ('datetime', models.CharField(max_length=64)),
            ],
        ),
    ]
