# Generated by Django 3.2.2 on 2021-06-05 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('industry', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='aticles',
            new_name='Articles',
        ),
    ]
